import './globals.css';

import type { Metadata } from 'next';
import { Open_Sans, Quicksand } from 'next/font/google';

import Navbar from '@/components/Navbar';
import { ResultProvider } from '@/utils/hooks/resultContext';

import Provider from './provider';

const quickSand = Quicksand({
    subsets: ['latin'],
    variable: '--font-quickSand',
    preload: true
});

const openSans = Open_Sans({
    subsets: ['latin'],
    variable: '--font-openSans',
    preload: true
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${quickSand.variable} ${openSans.variable} no-scrollbar font-openSans`}>
                <Provider>
                    <ResultProvider>
                        <Navbar />
                        {children}
                    </ResultProvider>
                </Provider>
            </body>
        </html>
    );
}
